on:
  push: {}
  workflow_dispatch: {}

jobs:
  echo:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: echo foo
        run: echo "foo" | grep 'o'

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18

      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: test
        run: ./gradlew test

      - name: show success
        run: echo "SUCCESS"
